
version: 2.0
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Testing
          command: | 
            gradle test
      - store_test_results:
          path: build/test-results
      - persist_to_workspace:
          root: .
          paths:
            - .
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Building
          command: | 
            gradle jar
      - store_artifacts:
          path: build/libs
          destination: prefix
      - persist_to_workspace:
          root: .
          paths:
            - .
workflows:
  version: 2
  two-job-workflow:
    jobs:
      - test
      - build:
          requires:
            - test